- name: Duplicate Job Template
  hosts: localhost
  vars:
    job_template_id: 14  # Replace with the actual ID of the job template to duplicate
  tasks:
    - name: Get the original job template
      uri:
        url: "{{ lookup('env', 'AWX_HOST') }}/api/v2/job_templates/{{ job_template_id }}/"
        method: GET
        user: "{{ lookup('env', 'AWX_USER') }}"
        password: "{{ lookup('env', 'AWX_PASSWORD') }}"
        return_content: yes
      register: original_template

    - name: Create a copy of the template
      awx.awx.job_template:
        tower_host: "{{ lookup('env', 'AWX_HOST') }}"
        username: "{{ lookup('env', 'AWX_USER') }}"
        password: "{{ lookup('env', 'AWX_PASSWORD') }}"
        name: "{{ (original_template.json.name ~ ' - Copy') }}"
        job_type: "{{ original_template.json.job_type }}"
        inventory: "{{ original_template.json.inventory }}"
        project: "{{ original_template.json.project }}"
        playbook: "{{ original_template.json.playbook }}"
        extra_vars: "{{ original_template.json.extra_vars }}"
        credentials: "{{ original_template.json.credentials }}"
        state: "present"
