---
- name: Get free disk space
  hosts: all
  tasks:
    - name: Get disk usage
      command: df -h
      register: disk_usage

    - name: Show disk usage
      debug:
        msg: "{{ disk_usage.stdout }}"
