---
- name: Write directly to NFS
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    - name: Install NFS client (if missing)
      package:
        name: nfs-utils
        state: present
      delegate_to: localhost
      run_once: true

    - name: Create mount point
      file:
        path: /mnt/nfs
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Mount NFS share
      mount:
        path: /mnt/nfs
        src: 10.1.0.100:/home/gtb/share_dir
        fstype: nfs
        state: mounted
      delegate_to: localhost
      run_once: true

    - name: Write file to NFS
      copy:
        content: "Hello from AWX job {{ inventory_hostname }}"
        dest: "/mnt/nfs/job-{{ inventory_hostname }}.txt"
      delegate_to: localhost
      run_once: true
