---
- name: Write to NFS via execution node
  hosts: all
  gather_facts: no

  tasks:

    - name: Write file to NFS through exe01
      copy:
        content: |
          AWX NFS TEST
          Inventory Host: {{ inventory_hostname }}
          Job ID: {{ tower_job_id }}
        dest: "/mnt/awx-logs/job-{{ inventory_hostname }}.txt"
      delegate_to: 10.1.0.80
