---
- name: Demo Ruleset for Webhook
  hosts: all

  sources:
    - ansible.eda.generic:
        host: 127.0.0.1
        port: 7000

  rules:
    - name: Run Demo Job Template
      condition: event.payload.message == "Hello EDA"
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
