---
- name: Rulebook to print debug message based on webhook event
  hosts: testHost
  gather_facts: false

  sources:
      - ansible.eda.webhook:
          host: 127.0.0.1
          port: 6000

  rules:
    - name: Run Demo Job Template
      condition: event.payload.message == "Hello EDA"
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
