- name: Listen for events on a webhook
  hosts: all
  # Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000
  # Define the conditions we are looking for
  rules:
    - name: Demo rule
      condition: event.meta.headers is defined 
      # Define the action we should take should the condition be met
      action:
        run_job_template:
          name: Ansible-Windows-Template
          organization: MyOrg
